repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: uv run isort --settings-file ./.isort.cfg .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: uv run black --config .black .
        language: system
        types: [ python ]
        pass_filenames: true

      - id: flake8
        name: flake8
        entry: uv run flake8 --config .flake8 .
        language: system
        types: [ python ]
        pass_filenames: false